language: java
jdk: 
  - openjdk11
  
addons:
  sonarcloud:
    organization: 404notfoundpk
    token: adb4794db44740ef51a4f628e60da2aac6c6a6af
 
script:
  - mvn clean test -Pcoverage
  - mvn sonar:sonar -Dsonar.projectKey=404NotFoundPK_bookkeeper
