language: java
jdk: 
- openjdk11

addons:
 sonarcloud:
  organization: 404notfoundpk
  token: ae057812944d1f34d0c6a6c9a35c5d9670763a2d  
script:
- mvn verify -DfailIfNoTests=false sonar:sonar -Dsonar.projectKey=404NotFoundPK_ISW2-BOOKKEEPER 