language: java
jdk: 
  - openjdk11
  
addons:
  sonarcloud:
    organization: 404notfoundpk
    token: 031e440393604965254d5f1adbafbea0f8ff252a
 
script:
  - mvn test -Dcoverage=true sonar:sonar -Dsonar.projectKey=404notfoundpk_ISW2-BOOKKEEPER
