language: java
jdk: 
  - openjdk11
  
addons:
  sonarcloud:
    organization: 404notfoundpk
    token: b48482c0cb46dee9f00a30133236a6512178c1a8
 
script:
  - mvn test -Dcoverage=true sonar:sonar -Dsonar.projectKey=404notfoundpk_ISW2-BOOKKEEPER
